### ISSUE TITLE
Coverage Tests failing

### ISSUE THREAD

**Issue by User-DK** [seldon-code/hari-plotter#31]
Recently tried using the Hari Plotter package but all the tests are failing. Would I still be able to use the Package ?

Here are the images of the errors captured

![Screenshot at 2024-08-11 09-35-08](https://github.com/user-attachments/assets/7235c521-81b2-4c2d-a448-86edae6fc752)
![Screenshot at 2024-08-11 09-35-54](https://github.com/user-attachments/assets/5516ce4f-462b-4ba4-a5e5-aa6bbaae937a)
![Screenshot at 2024-08-11 09-36-14](https://github.com/user-attachments/assets/6bc402b4-b4df-4596-9b4a-0da75ce21b02)

Thanks..

**Comment by imtambovtcev** [comment]
I fixed the issue, please check if that worked for you

**Comment by User-DK** [comment]
![Screenshot at 2024-08-11 20-11-48](https://github.com/user-attachments/assets/67b62f6b-8291-4e3f-92d2-0aadcf8846ba)

I recreated the micromamba environment but it still fails. I think its related to not mentioning some package in the env on your side, dont know if I am correct..

Thanks..

**Comment by imtambovtcev** [comment]
I hope I've got the problem, check if the new fix worked for you

**Comment by User-DK** [comment]
Yess, now its fine with some warnings 
Closing this issue as resolved
Thanks..

![Screenshot at 2024-08-12 19-46-39](https://github.com/user-attachments/assets/0bf80c76-2691-47df-ae08-89635d19fddc)
![Screenshot at 2024-08-12 19-47-46](https://github.com/user-attachments/assets/ecb0ac6f-e903-4a33-96f7-a55398857a94)
